Revert "[user errors] compulsory case names, allow multiple (#110878)"
This reverts commit 11c7ef8c375f3fee55eca32bbe5863ea85c17477.

Reverted https://github.com/pytorch/pytorch/pull/110878 on behalf of https://github.com/kit1980 due to export/test_export.py::TestExport::test_multiple_definitions_same_name_dim - TypeError: UserError.init() missing 1 required positional argument: 'case_names' ([comment](https://github.com/pytorch/pytorch/pull/110878#issuecomment-1754360051))