Add missing TORCH_API annotation (#36391)
Summary:
Pull Request resolved: https://github.com/pytorch/pytorch/pull/36391

Without it I get

```
ImportError: /data/users/ezyang/pytorch-tmp/torch/lib/libtorch_python.so: undefined symbol: _ZN5torch3jit18checkDoubleInRangeEd
```

when I build with DEBUG=1

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

Test Plan: Imported from OSS

Differential Revision: D20964292

Pulled By: ezyang

fbshipit-source-id: b2569f5813c6490de51372e70029648a36891e7a