[MPS] Fix `determine_backend_memory_format` logic (#151042)
If input is channels last than MPS will return a channels last output

This fixed `GPUTests.test_convolution_4_mps` from test_torchinductor.py

That previous failed with
```
AssertionError: expected size 3==3, stride 1==192 at dim=1; expected size 12==12, stride 48==16 at dim=2; expected size 16==16, stride 3==1 at dim=3
```
As FakeTensor implementation of conv returned `Contiguous`, rather than `ChannelLast` layout on MacOS-15 or later.
This doesn't seem to be very well documented, so will try to document the call path for `ExternKernel` invocation for `aten::convolution`:
 - First inductor decomp defined here is called
 https://github.com/pytorch/pytorch/blob/3e9c8f812fad5c56af9efbb2a3021c4f53ccdbcd/torch/_inductor/kernel/conv.py#L424-L425

- Then it goes thru FakeTensor decomposition implemented here
https://github.com/pytorch/pytorch/blob/7a9405f12d99fcdf7f3b9959155eabc51da4b52b/torch/_subclasses/fake_impls.py#L739-L740
- Finally it goes down to convolution meta registrations implemented here
https://github.com/pytorch/pytorch/blob/7a9405f12d99fcdf7f3b9959155eabc51da4b52b/torch/_meta_registrations.py#L2416-L2417

Pull Request resolved: https://github.com/pytorch/pytorch/pull/151042
Approved by: https://github.com/dcci