Revert "Adding entry-point based support for out-of-tree rendezvous plugins (#132633)"
This reverts commit 982694a4f37cc805e8c21d46b05cfc7ec63ce1c4.

Reverted https://github.com/pytorch/pytorch/pull/132633 on behalf of https://github.com/ZainRizvi due to Sorry but this is causing internal tests to fail with the error `ImportError: cannot import name '_register_out_of_tree_handlers' from 'torch.distributed.elastic.rendezvous.registry'` ([comment](https://github.com/pytorch/pytorch/pull/132633#issuecomment-2315716201))