Revert "Remove Caffe2 python code (#126035)"
This reverts commit a245842fad5a68bd253970cd7ce4f6bbe74d5fa3.

Reverted https://github.com/pytorch/pytorch/pull/126035 on behalf of https://github.com/jeanschmidt due to Seems to have introduced lint error: Error: Module 'onnx' has no attribute 'numpy_helper' ([comment](https://github.com/pytorch/pytorch/pull/126035#issuecomment-2110570863))