Revert "Support masked_fill (#88736)"
This reverts commit d0285d886e109fc88ecbeb6b2c5027ec65cd7044.

Reverted https://github.com/pytorch/pytorch/pull/88736 on behalf of https://github.com/kit1980 due to Inductor tests are failing with AttributeError: module 'torch._inductor.codecache' has no attribute 'valid_vec_isa_list'