Revert "change pre_autograd to pre_dispatch tracing (#101818)"
This reverts commit e781f626d40c825dc6ea38c27f2c96f231028ed9.

Reverted https://github.com/pytorch/pytorch/pull/101818 on behalf of https://github.com/izaitsevfb due to Breaks internal builds see D46629736 TypeError: wrap_key() got an unexpected keyword argument pre_autograd ([comment](https://github.com/pytorch/pytorch/pull/101818#issuecomment-1587837667))